### ISSUE TITLE
Can one write an instance of Cartesian for DownStar 

### ISSUE THREAD

**Issue by yuanw** [hablapps/DontFearTheProfunctorOptics#6]
I don't think there is an valid implementation of Cartesian for DownStar. I cannot find it in the [profunctors library](http://hackage.haskell.org/package/profunctors-5.3/docs/Data-Profunctor.html#t:Costar) . If so, maybe it is worth mentioning that it is impossible for write an instance of Cartesian for DownStar. 

BTW I enjoy the serial very much, thank you for putting it together.

**Comment by neutropolis** [comment]
You're right, there's no such implementation and the text leads to confusion. Would you like to submit a PR adapting that sentence to accept it as a contribution? Glad you liked it!
