### ISSUE TITLE
Lens type deeper explanation 

### ISSUE THREAD

**Issue by djleonskennedy** [hablapps/DontFearTheProfunctorOptics#8]
Hello 
I'm new in Opticts, could you clary if am i correct that the type parameters mean

data Lens s t a b = Lens { view   :: s -> a
                         , update :: (b, s) -> t }

-- "s" whole data
-- "t" whole new data
-- "a" focus related to "s"
-- "b" focus related to "t"

is it correct ?

Thank you

**Comment by neutropolis** [comment]
Yes, that's correct. Indeed, a nice introductory example of a polymorphic lens is `π1 :: Lens (a, c) (b, c) a b` (where `s = (a, c)` and `t = (b, c)`) that projects the first component of a tuple. You can find the implementation for that signature in the first part of these articles. I hope that helps!

**Comment by djleonskennedy** [comment]
@jeslg Thank you, you've made awesome article!
